# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DigiPen Student Senate
email: senate-webmaster@digipen.edu
description: DigiPen Student Senate
baseurl: "/digipen-student-senate" # the subpath of your site, e.g. /blog
url: "digipen-student-senate.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  senatewebmaster-temp

meeting:
  senate: 
    location: Plato
    time: Wednesdays, 3:30 - 4:30pm
  CS: 
    location: Michaelangelo
    time: Thursdays, 2:30 - 3:30pm (bi-weekly)
  CE:
    location: Archidemes
    time: Thursdays, 1:00 - 2:00pm (bi-weekly)
  GAM:
    location: Michaelangelo
    time: Fridays, 12:30 - 1:00pm
  Design:
    location: Hokusai
    time: Tuesdays, 11:30 - 12:30pm
  Art:
    location: Hokusai
    time: Tuesdays, 10:10 - 11:10 (bi-weekly)
  Audio:
    location: Room
    time: Day, Time

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
